jaffle_shop:

  target: ducklake
  outputs:
    dev:
      type: duckdb
      path: 'jaffle_shop.duckdb'
    ducklake:
      type: duckdb
      path: 'jaffle_shop.duckdb'
      extensions:
        - ducklake
      attach:
        - path: ducklake:metadata.ducklake
          alias: ducklake
          options:
            data_path: s3://my-s3-bucket
      threads: 1
